---

- name: Configure interface
  gather_facts: false
  hosts: 10.10.99.102
  tasks:
    - name: Create VLAN 10
      ios_config:
        lines:
          - vlan 10
          - name STUD1

    - name: Create VLAN 20
      ios_config:
        lines:
          - vlan 20
          - name STUD2

    - name: Set up access ports for vlan 10
      ios_config:
        lines:
          - switchport access vlan 10
        parents: interface range Fa0/4-13

    - name: Set up access ports for vlan 20
      ios_config:
        lines:
          - switchport access vlan 20
        parents: interface range Fa0/14-23

    - name: Set up port-channel
      ios_config:
        lines:
          - switchport mode trunk
        parents: interface Port-channel1

    - name: Apply port-channel to interface 1
      ios_config:
        lines:
          - switchport mode trunk
          - channel-group 1 mode active
          - no shutdown
        parents: interface Fa0/2

    - name: Apply port-channel to interface 2
      ios_config:
        lines:
          - switchport mode trunk
          - channel-group 1 mode active
          - no shutdown
        parents: interface Fa0/3